

import micropython
import math

try:
    from ulab import numpy as np
except ImportError:
    import numpy as np

S0_INIT = micropython.const(0)
S1_RUN  = micropython.const(1)

# ============================================================
# PRECOMPUTED MATRICES -- generated by observer_design.py
# tau=0.20  K=0.01527  r=0.035  W=0.141  Ts=0.020
# Observer poles: [-10.0, -7.0, -6.2, -5.0]
# Discrete poles |z|: [0.905, 0.884, 0.869, 0.819]
# ============================================================

Ad = [
    [8.94908994e-01,  9.92828107e-03, -4.01826383e-04,  2.98806104e-03],
    [9.92828107e-03,  8.94908994e-01, -4.01826383e-04, -2.98806104e-03],
    [3.01373069e-04,  3.01373069e-04,  8.18729278e-01, -3.71413368e-17],
    [-3.98493515e-03, 3.98493515e-03, -7.40176547e-17,  8.67303560e-01],
]

Bd_aug = [
    [1.44526553e-03,  7.86702165e-06,  4.09498057e-04, -7.67167373e-06, -2.95865057e-03, -4.20413431e-02],
    [7.86702165e-06,  1.44526553e-03, -7.67167373e-06,  4.09498057e-04,  2.95865057e-03,  4.20413431e-02],
    [2.41996607e-07,  2.41996607e-07,  9.06353612e-02,  9.06353612e-02,  3.70338023e-17,  5.60358049e-18],
    [-3.18117009e-06, 3.18117009e-06, -9.26301995e-03,  9.26301995e-03,  1.31390354e-01,  1.74874856e-03],
]


_METERS_PER_COUNT = -(2.0 * math.pi * 0.035) / (12 * 120)  
_Ts = 0.020  


class task_observer:
    def __init__(self,
                 left_enc, right_enc,
                 heading_share, yawrate_share,
                 effort_L_share, effort_R_share,
                 vL_share, vR_share, speed_share, yaw_share,
                 xpos_share, ypos_share):

        self._state = S0_INIT

        self._left_enc  = left_enc
        self._right_enc = right_enc
        self._phi       = heading_share
        self._psi       = yawrate_share
        self._uL        = effort_L_share
        self._uR        = effort_R_share

        self._vL    = vL_share
        self._vR    = vR_share
        self._spd   = speed_share
        self._yaw   = yaw_share
        self._xpos  = xpos_share
        self._ypos  = ypos_share

        self._Ad     = np.array(Ad)
        self._Bd_aug = np.array(Bd_aug)

        self._x = np.array([0.0, 0.0, 0.0, 0.0])

        self._prev_posL = 0
        self._prev_posR = 0

        self._x_pos = 0.0
        self._y_pos = 0.0

        print("Observer Task object instantiated")

    def _get_encoder_vel_ms(self):
        """Return encoder velocities in m/s since last call."""
        posL = self._left_enc.get_position()
        posR = self._right_enc.get_position()
        dL = (posL - self._prev_posL) * _METERS_PER_COUNT / _Ts
        dR = (posR - self._prev_posR) * _METERS_PER_COUNT / _Ts
        self._prev_posL = posL
        self._prev_posR = posR
        return dL, dR

    def run(self):
        while True:

            if self._state == S0_INIT:
                self._prev_posL = self._left_enc.get_position()
                self._prev_posR = self._right_enc.get_position()
                psi0 = float(self._psi.get())
                self._x = np.array([0.0, 0.0, 0.0, psi0])
                self._state = S1_RUN

            elif self._state == S1_RUN:
                
                vL_enc, vR_enc = self._get_encoder_vel_ms()

                phi_meas = float(self._phi.get())
                psi_meas = float(self._psi.get())
                uL = float(self._uL.get())
                uR = float(self._uR.get())

              
                u_aug = np.array([uL, uR, vL_enc, vR_enc, phi_meas, psi_meas])

                
                self._x = (np.dot(self._Ad, self._x) +
                           np.dot(self._Bd_aug, u_aug))

                vL_hat  = float(self._x[0])
                vR_hat  = float(self._x[1])
                s_hat   = float(self._x[2])
                psi_hat = float(self._x[3])

                
                spd_meas = (vL_enc + vR_enc) / 2.0
                self._x_pos += math.cos(phi_meas) * spd_meas * _Ts
                self._y_pos += math.sin(phi_meas) * spd_meas * _Ts

               
                self._vL.put(vL_hat)
                self._vR.put(vR_hat)
                self._spd.put(s_hat)
                self._yaw.put(psi_hat)
                self._xpos.put(self._x_pos)
                self._ypos.put(self._y_pos)


            yield self._state
